const express=require('express');
const router=express.Router();
const controller=require('../controller/pages');
const compilerController=require('../controller/compiler');
const isAuth=require("../middleware/isAuth");
router.get('/',controller.getHome);
router.get('/home',controller.getHome);
router.get('/compiler',isAuth,controller.getCompiler);
router.get('/share',isAuth,controller.getShare);
router.get('/practice',isAuth,controller.getPractice);
router.get('/practice/easy',isAuth,controller.getEasyProblem);
router.get('/practice/medium',isAuth,controller.getMediumProblem);
router.get('/practice/hard',isAuth,controller.getHardProblem);
router.post('/logout',isAuth,controller.getLogout);
router.post('/compiler',compilerController.getCodeText);
module.exports=router;
